export const getCounties = () => [
  { id: 'Antrim', title: 'Antrim' },
  { id: 'Armagh', title: 'Armagh' },
  { id: 'Carlow', title: 'Carlow' },
  { id: 'Cavan', title: 'Cavan' },
  { id: 'Clare', title: 'Clare' },
  { id: 'Cork', title: 'Cork' },
  { id: 'Donegal', title: 'Donegal' },
  { id: 'Down', title: 'Down' },
  { id: 'Dublin', title: 'Dublin' },
  { id: 'Fermanagh', title: 'Fermanagh' },
  { id: 'Galway', title: 'Galway' },
  { id: 'Kerry', title: 'Kerry' },
  { id: 'Kildare', title: 'Kildare' },
  { id: 'Kilkenny', title: 'Kilkenny' },
  { id: 'King_s_Co_', title: "King's Co. (Offaly)" },
  { id: 'Leitrim', title: 'Leitrim' },
  { id: 'Limerick', title: 'Limerick' },
  { id: 'Londonderry', title: 'Londonderry' },
  { id: 'Longford', title: 'Longford' },
  { id: 'Louth', title: 'Louth' },
  { id: 'Mayo', title: 'Mayo' },
  { id: 'Meath', title: 'Meath' },
  { id: 'Monaghan', title: 'Monaghan' },
  { id: 'Queen_s_Co_', title: "Queen's Co. (Laois)" },
  { id: 'Roscommon', title: 'Roscommon' },
  { id: 'Sligo', title: 'Sligo' },
  { id: 'Tipperary', title: 'Tipperary' },
  { id: 'Tyrone', title: 'Tyrone' },
  { id: 'Waterford', title: 'Waterford' },
  { id: 'Westmeath', title: 'Westmeath' },
  { id: 'Wexford', title: 'Wexford' },
  { id: 'Wicklow', title: 'Wicklow' },
]

export const getSexes = () => [
  { id: 'M', title: 'Male' },
  { id: 'F', title: 'Female' },
  { id: 'both', title: 'Both' },
]

export const getYears = () => [
  { id: '1901', title: '1901' },
  { id: '1911', title: '1911' },
]
